version: '2'

services:
  # this is our kafka cluster.
  kafka-cluster:
    image: landoop/fast-data-dev
    environment:
      ADV_HOST: 127.0.0.1         # Change to 192.168.99.100 if using Docker Toolbox
      RUNTESTS: 0                 # Disable Running tests so the cluster starts faster
    volumes:
      - ./connect-tutorial:/tutorial
    ports:
      - 2181:2181                 # Zookeeper
      - 3030:3030                 # Landoop UI
      - 8081-8083:8081-8083       # REST Proxy, Schema Registry, Kafka Connect ports
      - 9581-9585:9581-9585       # JMX Ports
      - 9092:9092                 # Kafka Broker

  # if elasticsearch fails to start with an error message like this:
  # ERROR: [1] bootstrap checks failed
  #        [1]: max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]
  # Run the following command to increase memory on the Docker HOST:
  # $ sysctl -w vm.max_map_count=262144
  elasticsearch:
    image: elasticsearch:6.5.1
    ports:
      - 9200:9200
      #- 9300:9300