version: "3.1"

services:
  zookeeper:
    build:
      context: ./Zookeeper
      dockerfile: Dockerfile
    ports:
      - 2181:2181

  kafka:
    build:
      context: ./Kafka
      dockerfile: Dockerfile
      args:
        - ZOOKEEPER_HOST=zookeeper
        # I tried to specify "kafka" as advertised host but it didn't work. Localhost worked though!
        # Is this used for security check? or client consumers receive this redirect?
        # https://rmoff.net/2018/08/02/kafka-listeners-explained/
        - KAFKA_ADVERTISED_HOST=localhost
    ports:
      - 9092:9092
    depends_on:
      - zookeeper

  # if elasticsearch fails to start with an error message like this:
  # ERROR: [1] bootstrap checks failed
  #        [1]: max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]
  # Run the following command to increase memory on the Docker HOST:
  # $ sysctl -w vm.max_map_count=262144
  elasticsearch:
    image: elasticsearch:6.5.1
    ports:
      - 9200:9200
      #- 9300:9300

